# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(365, 483)
        StackedWidget.setStyleSheet("")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(36, 31, 49);")
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.combobox = QtWidgets.QComboBox(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.combobox.setFont(font)
        self.combobox.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(145, 65, 172);\n"
"    border-radius: 10px;\n"
"    height: 50;\n"
"}\n"
"QComboBox:hover {\n"
"    background-color: rgb(129, 61, 156);\n"
"}\n"
"QComboBox:pressed {\n"
"    background-color: rgb(97, 53, 131);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(36, 31, 49);\n"
"    border: 2px solid;\n"
"    border-color: rgb(145, 65, 172);\n"
"    padding: 5px;\n"
"}")
        self.combobox.setObjectName("combobox")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.verticalLayout.addWidget(self.combobox)
        self.example_label = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.example_label.setFont(font)
        self.example_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.example_label.setObjectName("example_label")
        self.verticalLayout.addWidget(self.example_label)
        self.input_field = QtWidgets.QLineEdit(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.input_field.setFont(font)
        self.input_field.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 245, 244);\n"
"border: 2px solid;\n"
"border-color: rgb(145, 65, 172);\n"
"border-radius: 10px;\n"
"height: 50;")
        self.input_field.setText("")
        self.input_field.setObjectName("input_field")
        self.verticalLayout.addWidget(self.input_field)
        self.check_button = QtWidgets.QPushButton(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.check_button.setFont(font)
        self.check_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(145, 65, 172);\n"
"    border-radius: 10px;\n"
"    height: 50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(129, 61, 156);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(97, 53, 131);\n"
"}")
        self.check_button.setFlat(False)
        self.check_button.setObjectName("check_button")
        self.verticalLayout.addWidget(self.check_button)
        self.skip_button = QtWidgets.QPushButton(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.skip_button.setFont(font)
        self.skip_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(53, 132, 228);\n"
"    border-radius: 10px;\n"
"    height: 50;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(28, 113, 216);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(26, 95, 180);\n"
"}")
        self.skip_button.setObjectName("skip_button")
        self.verticalLayout.addWidget(self.skip_button)
        self.frame = QtWidgets.QFrame(parent=self.page)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.skipped_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.skipped_label.setFont(font)
        self.skipped_label.setStyleSheet("")
        self.skipped_label.setObjectName("skipped_label")
        self.verticalLayout_3.addWidget(self.skipped_label)
        self.solved_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.solved_label.setFont(font)
        self.solved_label.setStyleSheet("")
        self.solved_label.setObjectName("solved_label")
        self.verticalLayout_3.addWidget(self.solved_label)
        self.mistakes_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.mistakes_label.setFont(font)
        self.mistakes_label.setStyleSheet("")
        self.mistakes_label.setObjectName("mistakes_label")
        self.verticalLayout_3.addWidget(self.mistakes_label)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        StackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 162, 105);")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(237, 51, 59);")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        StackedWidget.addWidget(self.page_3)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "Math trainer"))
        self.combobox.setItemText(0, _translate("StackedWidget", "Addition within 100"))
        self.combobox.setItemText(1, _translate("StackedWidget", "Multiplication within 10"))
        self.example_label.setText(_translate("StackedWidget", "5+5="))
        self.input_field.setPlaceholderText(_translate("StackedWidget", "Enter the answer..."))
        self.check_button.setText(_translate("StackedWidget", "CHECK"))
        self.skip_button.setText(_translate("StackedWidget", "Skip this example"))
        self.skipped_label.setText(_translate("StackedWidget", "Skipped examples:"))
        self.solved_label.setText(_translate("StackedWidget", "Solved examples:"))
        self.mistakes_label.setText(_translate("StackedWidget", "Mistakes:"))
        self.label_5.setText(_translate("StackedWidget", "Correctly"))
        self.label_6.setText(_translate("StackedWidget", "Wrongly"))
